### ISSUE TITLE
Improve naming convention of the output branches

### ISSUE THREAD

**Issue by ram1123** [ram1123/nanoAOD_vvVBS#25]

**Comment by vukasinmilosevic** [comment]
Maybe we can use next week's meeting to sit down and write a .txt file with all the changes needed. Basically, the quickest way to produce Run 3 results would be to use the same naming convention as the BBF flat trees used. @YujiLee301 @ram1123

**Comment by ram1123** [comment]
List of branches name should follow this file: https://github.com/ram1123/Fiducial_XS/blob/debugStatUncIssue/Inputs/observables_list.yml

@vukasinmilosevic Right?

**Comment by ram1123** [comment]
Few missing variables: 

 finalState, mass4e, mass4mu 

@YujiLee301

**Comment by ram1123** [comment]
Few To do in this list:

- [x] Update weight branch
- [x] Add Puppi MET
- [x] Add cross-section values
- [x] Add the functionality for the total number of entries

**Comment by YujiLee301** [comment]
XS values： ggH 23.16 VBF 4.224 WminusH 0.5803 WplusH 0.9218 ZH 0.8428 ttH 0.5806

**Comment by ram1123** [comment]
Its done by @YujiLee301. So, closing it.
